version: '3.5'

services:
  postgres:
    container_name: postgres_exception_db
    image: postgres
    environment:
      POSTGRES_USER: exception_miner
      POSTGRES_PASSWORD: exception_miner
      POSTGRES_DB: exception_miner
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
